### ISSUE TITLE
Unknown column since latest update

### ISSUE THREAD

**Issue by Ahmed-Elrayes** [ekvedaras/laravel-query-intellij#100]
Hello, since the last update i keep getting unknown column even though i'm sure that i have the datasource added and even selected the database i want for the query in settings..
![image](https://user-images.githubusercontent.com/30704271/192062342-e5f56e54-7430-4a7c-a639-3428b1090289.png)

**Comment by ekvedaras** [comment]
Hi. Can you share the full code statement?

**Comment by Ahmed-Elrayes** [comment]
This is one statement.
![image](https://user-images.githubusercontent.com/30704271/192091297-974328be-4010-4464-8866-5f4704eb19c4.png)

This is another one 
![image](https://user-images.githubusercontent.com/30704271/192091325-ab208404-1690-4338-b3d9-abcc8f70cc64.png)

**Comment by ekvedaras** [comment]
Does `CompetitorUser` model has `$table` property defined? How is the table itself named? What do your plugin settings look like?

For the second, just out of curiosity - does it work if you rename first declaration of `$query` variable to something else, but leave `$query = match` name variable name unchanged? Or vice versa

**Comment by Ahmed-Elrayes** [comment]
```CompetitorUser``` has ```$table``` in it yes. and the table name is ```competitors_users``` 
the valriable ```$query``` can be renamed and still have the same issue, actually this issue is in the whole project.
since you mentioned plugin settings, it seems that this issue occurred only to this project, all my other projects are working fine, and it's weird because i'm pretty sure i did not change any setting, it just happened once i updated the plugin.

and here is the settings for it 
![image](https://user-images.githubusercontent.com/30704271/192097940-44cfca65-8b52-49cf-a1a1-0a06b333e94c.png)

**Comment by ekvedaras** [comment]
If you temporarily unselect `Filter data sources` ?  Is it for sure correct dabase selected? Is it refreshed and up to date in `Databases` toolbar view?

**Comment by Ahmed-Elrayes** [comment]
the issue still persists if i unselect filter data sources.
the database is for sure selected yeah i even deleted the datasource in Database toolbar and added it again and still persists.

**Comment by Ahmed-Elrayes** [comment]
Managed to fix it finally, had to delete the laravel-query-settings.xml file from .idea folder
![image](https://user-images.githubusercontent.com/30704271/192099792-b1bcc977-b648-43df-bb91-b1a54103a64c.png)

**Comment by Ahmed-Elrayes** [comment]
here is how it did look inside
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="LaravelQuerySettings">
    <option name="filterDataSources" value="true" />
    <option name="filteredDataSources">
      <set>
        <option value="30eca40e-d219-4cd8-bf22-f78372aabbbd&lt;-/lq/-&gt;linda" />
      </set>
    </option>
    <option name="tablePrefix" value=" " />
  </component>
</project>
```

**Comment by ekvedaras** [comment]
Most likely. Should probably trim this value before saving. Don't think in any database spaces are allowed in table names 🤔

**Comment by Ahmed-Elrayes** [comment]
i actually don't do any table prefixes, so i'm not sure why it was added

**Comment by ekvedaras** [comment]
Most likely by accident

**Comment by Ahmed-Elrayes** [comment]
i see, thanks a lot.
i hope at least you can make something for this in the future to trim any spaces before saving.
i will close this issue.

**Comment by cAstraea** [comment]
Had the same issue. Deleting the .xml fixed it. Thx [Ahmed-Elrayes](https://github.com/Ahmed-Elrayes)

**Comment by Ahmed-Elrayes** [comment]
You are welcome, glad that it helped you.
