### ISSUE TITLE
Not compatible with EAP

### ISSUE THREAD

**Issue by olivernybroe** [ekvedaras/laravel-query-intellij#12]
Nice to see you got a version ready for testing 👍 

I have a problem with not being able to install it on EAP versions, as the current EAP is 2021.1 😃

**Comment by ekvedaras** [comment]
I wonder how am I going to keep up with new versions coming out 😀 Might have to switch to EAP myself 🤔 Will update today 🙂

**Comment by ekvedaras** [comment]
Makes sense. And I assume this is why you removed the verifier part as well?

**Comment by olivernybroe** [comment]
@ekvedaras have I? 😅 Nope that's not intentional.

**Comment by ekvedaras** [comment]
Ah ok it's there now 😀 I could be wrong, it was long time ago when I looked 😀

**Comment by ekvedaras** [comment]
https://github.com/ekvedaras/laravel-query-intellij/releases/tag/v0.0.3
