### ISSUE TITLE
Compatibility with old PhpStorm version ?

### ISSUE THREAD

**Issue by din2011** [ekvedaras/laravel-query-intellij#17]
Hi Sir... can you made it compatible with old PhpStorm version ?

I have old PhpStorm version 2019.2

**Comment by ekvedaras** [comment]
Would you indulge me why you are on such an old version? 🙂 I will check today if that's possible.

**Comment by din2011** [comment]
> Would you indulge me why you are on such an old version?  I will check today if that's possible.

because that's last I paid (subscribed) to Jetbrains license... fallback perpetual version

currently don't have enough funds to continue subscribing to new version

**Comment by ekvedaras** [comment]
I see. Well changing the lowest allowed version is easy. The question is: will it work? 😀

**Comment by din2011** [comment]
Subscription expired on 26 August 2020... it was not so old Sir

**Comment by din2011** [comment]
tqvm... I will try and give feedback here

**Comment by ekvedaras** [comment]
I'll try to make it today. But keep in mind it will take a day or two for JetBrains to approve new release.

**Comment by din2011** [comment]
tqvm again

**Comment by ekvedaras** [comment]
I pushed the updated, but I'm now checking compatibility check on Jetbrains plugin page and see some missing functions. And now I remember there were some interface changes in recent phpstorm versions. So I'm a bit afraid I won't be able to support it. The only thing I could do is branch of and make one version that supports older phpstorm. However that won't be published, so you'll have to do manual install from disc and I don't think I intend to keep maintaining that for a long time 🙂 But at least you would have some working version, although without updates 🙂

**Comment by ekvedaras** [comment]
So 2019.2 is actually pretty old 🙂 I've adapted the code, but doesn't seem to run properly. So this needs more investigation and time spent. I will keep trying, but this will be lower priority than other issues 🙂

**Comment by ekvedaras** [comment]
After lots of trying I decided to cancel this adventure. There is no clear reason why it doesn't work. The code simple does not run completion providers and inspectors like it should. Its kinda hard to find old docs either. I'd better focus on new improvements. Sorry for the inconvenience. I advice contacting PhpStorm team, they may be able to offer you some discount as I've seen they sometimes do on twitter.

I'm closing this issue, if somebody wants to try implementing this, feel free to try.
