### ISSUE TITLE
Unknown column warning on operator

### ISSUE THREAD

**Issue by ordago** [ekvedaras/laravel-query-intellij#35]
![image](https://user-images.githubusercontent.com/6376814/120086152-71846080-c0d5-11eb-9349-d791a2a8c35c.png)

It seems it has trouble identifying the operator when using the where with the array syntax.

![image](https://user-images.githubusercontent.com/6376814/120086225-e48dd700-c0d5-11eb-981e-741c5469fbb7.png)

It shows no warning when using where the usual way.

**Comment by ekvedaras** [comment]
I'm working on a bit larger code update regarding indexes. I will address this during or after that if it's not fixed by someone else by then :)
