### ISSUE TITLE
`Model::create([])` completion

### ISSUE THREAD

**Issue by ekvedaras** [ekvedaras/laravel-query-intellij#40]
So in the end the inspection and completion work as they should.
```php
Model::create([
    '<caret>' => 'value',
])
```

However, as we're writing the code we get this:

```php
Model::create([
    'id' => 1,
    '<caret>'
]);
```

Technically caret is now inside array value and we don't want to complete in array values here, but we are actually writing a column at that moment. So, this needs to be somehow detected properly.

**Comment by hailwood** [comment]
This seems like the appropriate place to say it would be great if we could have support for

```php
$modelInstance->update([...]);
```

Side note, I'm writing a much simpler PhpStorm plugin than this at the moment (for a JS library) and they're not easy.
So kudos to you for what you've achieved here and I appreciate the work!

**Comment by ekvedaras** [comment]
It actually does support that. But like the issue mentions, you first need to have a value defined in order for the key to be completed 😄 Not ideal.. But without that check in place, it starts completing columns where it shouldn't. It is possible to improve the check which is the task here. I was a bit on vacation so had to put this on hold 🙂

Yeah, it is not easy. Docs are very basic and cover very little. A lot of examples are still in Java. Usually, your best bet is to explore the IDE codebase and hopefully find something that does what you need 😀 Good luck in your journey 👍

**Comment by ekvedaras** [comment]
Implemented. Will come with the next release.
