### ISSUE TITLE
No autocomplete and code not recognized

### ISSUE THREAD

**Issue by ThomasCollignon** [ekvedaras/laravel-query-intellij#53]
As you can see the `where` clauses are not recognized by the editor.

![image](https://user-images.githubusercontent.com/16621630/126936412-4c244942-f99d-4e1b-b450-cce19b6fce0d.png)

You can see on the right that the DB connection is ok.
Also, there is no autocomplete.
What did I miss ?

**Comment by ekvedaras** [comment]
Hi. Make sure you are using [laravel-ide-helper package](https://github.com/barryvdh/laravel-ide-helper) or [laravel-idea plugin](https://laravel-idea.com/docs/eloquent), as PhpStorm does not understand Laravel model references by default.
