### ISSUE TITLE
Unable to select a data source in the plugin UI

### ISSUE THREAD

**Issue by JackWH** [ekvedaras/laravel-query-intellij#66]
After a recent update of the plugin, I get the notification bubble prompting me to choose a data source, which takes me to this window:

<img width="1094" alt="Screenshot 2021-09-29 at 11 22 48" src="https://user-images.githubusercontent.com/627533/135250983-a07edd34-c559-4af0-87dc-a12308e98cd4.png">

However, clicking anywhere in the list does... absolutely nothing. I can't tick any of the boxes, or order/sort any of the columns. I can resize them, but that's the only interaction I can see to do with the window.

There's no errors or beeps — just appears to be totally non-responsive. I've tried invalidating caches + restarting, but it makes no difference.

(This issue aside, thanks for a great plugin!)

**Comment by ekvedaras** [comment]
Hey, I see in the screenshot "Filter data sources" checkbox is disabled. The table should become interactive once you enable that.

**Comment by JackWH** [comment]
@ekvedaras Thanks for the speedy reply... I'd tried that before, but it didn't work. However, I just tried again now and realised it _does_ work, but not when you click the checkboxes themselves — you have to click the label with the database name before the box will tick.

Thanks!

**Comment by ekvedaras** [comment]
Yeah I've noticed this before but I thought it was my corrupt test data 🤔 I will look into those checkboxes why they sometimes do not function properly when clicked directly.
