### ISSUE TITLE
Warning on alias

### ISSUE THREAD

**Issue by time4dev** [ekvedaras/laravel-query-intellij#68]
hello.
![image](https://user-images.githubusercontent.com/54905262/136918583-a582b698-05ae-4352-af14-bb17f5fc3b93.png)
example warning on alias table. Maybe I'm doing something wrong?
phpStorm latest. plugin updated.
autocomplete on alias work perfectly
![image](https://user-images.githubusercontent.com/54905262/136919898-44bb9cd8-947a-4dcb-9d22-7069cc5c494d.png)
problem only inside "leftJoin"
![image](https://user-images.githubusercontent.com/54905262/136920010-307c9a02-aea8-4fc3-ba48-03c33e53c8a4.png)

**Comment by ekvedaras** [comment]
Ok this one is a bit weird. I can't reproduce it. Tried to recreate similar scenarios and it just works 🤔
