### ISSUE TITLE
Unknown column inspection triggers for object string values

### ISSUE THREAD

**Issue by ekvedaras** [ekvedaras/laravel-query-intellij#96]
```php
SomeModel::create([
    'prop_1' => $val1,
    'prop_2' => $var = new SomeObject(
        prop1: 'Val1', // <--
    ),
]);
```

**Comment by LabSilo** [comment]
The same inspection triggers when using `relationship()->pluck('...')`
![image](https://user-images.githubusercontent.com/110684470/190899668-7e7464e2-24df-402e-baf2-5c5722e99e81.png)

![image](https://user-images.githubusercontent.com/110684470/190899752-0cac1f33-98f5-4267-adac-667265f374fd.png)

**Comment by ekvedaras** [comment]
Thanks for reporting 👍 Will look into

**Comment by ekvedaras** [comment]
Can't reproduce the issue with settings not persisting 🤷 
I've fixed the issue with column inspection in create method
